version: '3.8'

services:
  avalanche-l1:
    build: .
    container_name: avalanche-l1
    ports:
      # Avalanche primary network ports
      - "9650:9650"
      - "9651:9651"
      - "9652:9652"
      - "9654:9654"
      - "9656:9656"
      - "9658:9658"
      # L1 RPC ports (dynamic range)
      - "30000-40000:30000-40000"
    environment:
      - BLOCKCHAIN_NAME=myblockchain
      - CHAIN_ID=888
      - TOKEN_SYMBOL=TST
      - TOKEN_NAME=TST Token
      - VALIDATOR_MANAGER_OWNER=ewoq
    volumes:
      # Persist Avalanche CLI data
      - avalanche_data:/root/.avalanche-cli
      # Optional: Mount logs for easier access
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9650/ext/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  avalanche_data:
