services:
  avalanche-l1:
    build: .
    container_name: avalanche-l1-node
    ports:
      # Primary node API port
      - "9650:9650"
      # Staking port
      - "9651:9651"
      # Additional Avalanche ports
      - "9652:9652"
      - "9654:9654"
      - "9656:9656"
      - "9658:9658"
      # L1 node port (can vary)
      - "60172:60172"
    environment:
      # Load from default.env
      - BLOCKCHAIN_NAME=${BLOCKCHAIN_NAME:-myblockchain}
      - CHAIN_ID=${CHAIN_ID:-888}
      - TOKEN_SYMBOL=${TOKEN_SYMBOL:-TST}
      - TOKEN_NAME=${TOKEN_NAME:-TST Token}
    env_file:
      - configs/default.env
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Mount Avalanche CLI data directory for blockchain persistence
      - avalanche-data:/root/.avalanche-cli
      # Mount home directory for avalanche CLI state
      - avalanche-home:/root
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - avalanche-network

networks:
  avalanche-network:
    driver: bridge

volumes:
  avalanche-data:
    driver: local
  avalanche-home:
    driver: local
